system_config:
  conf_version: v1.1.1
  host: 127.0.0.1
  port: 12393
  config_alts_dir: characters
  tool_prompts:
    live2d_expression_prompt: live2d_expression_prompt
  group_conversation_prompt: group_conversation_prompt
character_config:
  conf_name: mao_pro-local
  conf_uid: mao_pro-local-001
  live2d_model_name: mao_pro-local
  character_name: mao_pro
  avatar: mao.png
  human_name: Human
  persona_prompt: '你是一个校园AI助手。

    请直接回答用户的问题，只提供与问题相关的信息。

    如果参考知识库，必须严格筛选与问题直接相关的内容。回答时使用自然流畅的语句，避免任何特殊符号或非常规字符，确保语音合成顺畅。

    '
  agent_config:
    conversation_agent_choice: basic_memory_agent
    agent_settings:
      basic_memory_agent:
        llm_provider: openai_compatible_llm
        faster_first_response: true
        segment_method: pysbd
      mem0_agent:
        vector_store:
          provider: qdrant
          config:
            collection_name: test
            host: localhost
            port: 6333
            embedding_model_dims: 1024
        llm:
          provider: ollama
          config:
            model: llama3.1:latest
            temperature: 0
            max_tokens: 8000
            ollama_base_url: http://localhost:11434
        embedder:
          provider: ollama
          config:
            model: mxbai-embed-large:latest
            ollama_base_url: http://localhost:11434
      hume_ai_agent:
        api_key: ''
        host: api.hume.ai
        config_id: ''
        idle_timeout: 15
    llm_configs:
      openai_compatible_llm:
        base_url: http://172.31.0.203:3001/api/v1/openai
        llm_api_key: K9XSJHQ-97JM73R-QVK786E-AT2HZKF
        organization_id: org_eternity
        project_id: project_glass
        model: open-llm-vtuber
        temperature: 1.0
        interrupt_method: user
      claude_llm:
        base_url: https://api.anthropic.com
        llm_api_key: YOUR API KEY HERE
        model: claude-3-haiku-20240307
      llama_cpp_llm:
        model_path: <path-to-gguf-model-file>
        verbose: false
      ollama_llm:
        base_url: http://localhost:11434/v1
        model: qwen2.5:latest
        temperature: 1.0
        keep_alive: -1
        unload_at_exit: true
      openai_llm:
        llm_api_key: Your Open AI API key
        model: gpt-4o
        temperature: 1.0
      gemini_llm:
        llm_api_key: Your Gemini API Key
        model: gemini-2.0-flash-exp
        temperature: 1.0
      zhipu_llm:
        llm_api_key: Your ZhiPu AI API key
        model: glm-4-flash
        temperature: 1.0
      deepseek_llm:
        llm_api_key: Your DeepSeek API Key
        model: deepseek-chat
        temperature: 0.7
      mistral_llm:
        llm_api_key: Your Mistral API key
        model: pixtral-large-latest
        temperature: 1.0
      groq_llm:
        llm_api_key: your groq API key
        model: llama-3.3-70b-versatile
        temperature: 1.0
  asr_config:
    asr_model: sherpa_onnx_asr
    azure_asr:
      api_key: azure_api_key
      region: eastus
      languages:
      - en-US
      - zh-CN
    faster_whisper:
      model_path: distil-medium.en
      download_root: models/whisper
      language: en
      device: auto
    whisper_cpp:
      model_name: small
      model_dir: models/whisper
      print_realtime: false
      print_progress: false
      language: auto
    whisper:
      name: medium
      download_root: models/whisper
      device: cpu
    fun_asr:
      model_name: iic/SenseVoiceSmall
      vad_model: fsmn-vad
      punc_model: ct-punc
      device: cpu
      disable_update: true
      ncpu: 4
      hub: ms
      use_itn: false
      language: auto
    sherpa_onnx_asr:
      model_type: sense_voice
      sense_voice: ./models/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/model.int8.onnx
      tokens: ./models/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-2024-07-17/tokens.txt
      num_threads: 4
      use_itn: true
      provider: cpu
    groq_whisper_asr:
      api_key: ''
      model: whisper-large-v3-turbo
      lang: ''
  tts_config:
    tts_model: gpt_sovits_tts
    azure_tts:
      api_key: azure-api-key
      region: eastus
      voice: en-US-AshleyNeural
      pitch: '26'
      rate: '1'
    bark_tts:
      voice: v2/en_speaker_1
    edge_tts:
      voice: zh-CN-XiaoxiaoNeural
    cosyvoice_tts:
      client_url: http://127.0.0.1:50000/
      mode_checkbox_group: 预训练音色
      sft_dropdown: 中文女
      prompt_text: ''
      prompt_wav_upload_url: https://github.com/gradio-app/gradio/raw/main/test/test_files/audio_sample.wav
      prompt_wav_record_url: https://github.com/gradio-app/gradio/raw/main/test/test_files/audio_sample.wav
      instruct_text: ''
      seed: 0
      api_name: /generate_audio
    cosyvoice2_tts:
      client_url: http://127.0.0.1:50000/
      mode_checkbox_group: 预训练音色
      sft_dropdown: 中文女
      prompt_text: ''
      prompt_wav_upload_url: https://github.com/gradio-app/gradio/raw/main/test/test_files/audio_sample.wav
      prompt_wav_record_url: https://github.com/gradio-app/gradio/raw/main/test/test_files/audio_sample.wav
      instruct_text: ''
      stream: false
      seed: 0
      speed: 1.0
      api_name: /generate_audio
    melo_tts:
      speaker: EN-Default
      language: EN
      device: auto
      speed: 1.0
    x_tts:
      api_url: http://127.0.0.1:8020/tts_to_audio
      speaker_wav: female
      language: en
    gpt_sovits_tts:
      api_url: http://172.31.0.203:9885/tts
      text_lang: zh
      ref_audio_path: /home/ubuntu/edmond/GPT-SoVITS-test/GPT-SoVITS/ref-data/liu-ref.wav
      prompt_lang: zh
      prompt_text: 匆匆，燕子去了有再来的时候
      text_split_method: cut3
      batch_size: '1'
      media_type: wav
      streaming_mode: 'false'
    fish_api_tts:
      api_key: ''
      reference_id: ''
      latency: balanced
      base_url: https://api.fish.audio
    coqui_tts:
      model_name: tts_models/en/ljspeech/tacotron2-DDC
      speaker_wav: ''
      language: en
      device: ''
    sherpa_onnx_tts:
      vits_model: /path/to/tts-models/vits-melo-tts-zh_en/model.onnx
      vits_lexicon: /path/to/tts-models/vits-melo-tts-zh_en/lexicon.txt
      vits_tokens: /path/to/tts-models/vits-melo-tts-zh_en/tokens.txt
      vits_data_dir: ''
      vits_dict_dir: /path/to/tts-models/vits-melo-tts-zh_en/dict
      tts_rule_fsts: /path/to/tts-models/vits-melo-tts-zh_en/number.fst,/path/to/tts-models/vits-melo-tts-zh_en/phone.fst,/path/to/tts-models/vits-melo-tts-zh_en/date.fst,/path/to/tts-models/vits-melo-tts-zh_en/new_heteronym.fst
      max_num_sentences: 2
      sid: 1
      provider: cpu
      num_threads: 1
      speed: 1.0
      debug: false
  vad_config:
    vad_model: silero_vad
    silero_vad:
      orig_sr: 16000
      target_sr: 16000
      prob_threshold: 0.4
      db_threshold: 60
      required_hits: 3
      required_misses: 24
      smoothing_window: 5
  tts_preprocessor_config:
    remove_special_char: true
    ignore_brackets: true
    ignore_parentheses: true
    ignore_asterisks: true
    ignore_angle_brackets: true
    translator_config:
      translate_audio: false
      translate_provider: deeplx
      tencent:
        secret_id: ''
        secret_key: ''
        region: ap-guangzhou
        source_lang: zh
        target_lang: ja
